name: CI/CD Pipeline for Node.js Dockerized App

on:
  push:
    branches:
      - master # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t my-node-app:latest .

    # Save Docker Image as tar file
    - name: Save Docker Image
      run: |
        docker save my-node-app:latest > my-node-app.tar

    # Upload the Docker Image tar to GitHub Actions artifacts
    - name: Upload Docker Image
      uses: actions/upload-artifact@v3
      with:
        name: my-node-app-image
        path: my-node-app.tar

    # Deploy to the server using SSH
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Stop and remove existing container
          docker stop node_app || true
          docker rm node_app || true

          # Create deployment directory
          mkdir -p /tmp/docker-deploy

          # Transfer Docker image tar
          scp my-node-app.tar /tmp/docker-deploy

          # Transfer .env file from GitHub secret
          echo "${{ secrets.ENV_FILE }}" > /tmp/docker-deploy/.env

          # Load Docker image
          sudo docker load < /tmp/docker-deploy/my-node-app.tar

          # Run Docker container with .env file
          sudo docker run -d --name node_app --env-file /tmp/docker-deploy/.env -p 80:3000 my-node-app:latest
